version: '2'
services:
    db:
        build: .
        restart: always
        environment:
        - "MYSQL_ROOT_PASSWORD=password"
        - "CLUSTER_NAME=galeracluster"
        - "SERVICE_NAME=test-galera-db"
        - "DEBUG=true" 
        - "BACKEND=consul"
        - "affinity:com.mariadb.host!=galeracluster"
        depends_on: 
            - registrator
        labels:
        - "com.mariadb.host=galeracluster"
        ports:
        - 3306:3306
        - 4567-4568:4567-4568
        - 4444:4444
    registrator:
        image: gliderlabs/registrator:master
        hostname: registrator
        depends_on: 
            - consul
        volumes:
        - "/var/run/docker.sock:/tmp/docker.sock"
        command: -internal consul://consul:8500
        restart: always
        environment:
        - "affinity:com.mariadb.host!=registrator"
        labels:
        - "com.mariadb.host=registrator"
    consul:
        image: "progrium/consul:latest"
        hostname: "consul"
        ports:
        - "8400:8400"
        - "8500:8500"
        - "8600:53/udp"
        command: "-server -bootstrap -ui-dir /ui"
        restart: always