version: '2'
services:
    db:
        build: .
        restart: always
        environment:
        - "MYSQL_ROOT_PASSWORD=password"
        - "CLUSTER_NAME=galeracluster"
        - "SERVICE_NAME=test-galera-db"
        - "DEBUG=true" 
        - "BACKEND=etcd"
        - "affinity:com.mariadb.host!=galeracluster"
        depends_on: 
            - registrator
        labels:
        - "com.mariadb.host=galeracluster"
        ports:
        - 3306:3306
        - 4567-4568:4567-4568
        - 4444:4444
    registrator:
        image: gliderlabs/registrator:master
        hostname: registrator
        depends_on: 
            - etcd
        volumes:
        - "/var/run/docker.sock:/tmp/docker.sock"
        command: -internal etcd://etcd:2379
        restart: always
        environment:
        - "affinity:com.mariadb.host!=registrator"
        labels:
        - "com.mariadb.host=registrator"
    etcd:
        image: "quay.io/coreos/etcd:v3.1.0"
        hostname: etcd
        ports: 
        - 2379-2380:2379-2380
        - 4001:4001
        - 7001:7001
        command: etcd -advertise-client-urls=http://etcd:2379,http://etcd:4001,http://127.0.0.1:2379,http://127.0.0.1:4001 -listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001
        restart: always